/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input wire [1:0] x


      // Outputs
    , output wire [2:0] result
    );
  wire signed [63:0] ds;
  reg [1:0] result_1;
  reg [1:0] c$case_alt;
  wire [1:0] c$case_alt_0;
  wire signed [63:0] c$ds_app_arg;
  wire signed [63:0] result_selection_res;
  wire signed [63:0] c$case_alt_selection_res;

  assign ds = $signed(c$ds_app_arg);

  assign result_selection_res = (ds >= 64'sd0) ? 64'sd1 : 64'sd0;

  always @(*) begin
    case(result_selection_res)
      64'sd1 : result_1 = c$case_alt;
      default : result_1 = {2 {1'bx}};
    endcase
  end

  assign c$case_alt_selection_res = (ds <= 64'sd2) ? 64'sd1 : 64'sd0;

  always @(*) begin
    case(c$case_alt_selection_res)
      64'sd1 : c$case_alt = c$case_alt_0;
      default : c$case_alt = {2 {1'bx}};
    endcase
  end

  assign c$case_alt_0 = $unsigned(ds);

  assign c$ds_app_arg = $unsigned({{(64-2) {1'b0}},x});

  assign result = (x == 2'b11) ? {1'b0,2'bxx} : {1'b1,result_1};


endmodule

