/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module topEntity
  #( parameter width = 64
	)
    ( // Inputs
      input wire  eta // clock
    , input wire  eta1 // reset
    , input wire  eta2 // enable

      // Outputs
    , output wire [width - 1:0] result
    );
    wire [width - 1:0] c$result_rec;
  reg [width - 1:0] c$app_arg = 1'd0;
  reg [width - 1:0] c$app_arg_0 = 1'd0;
  reg [width - 1:0] c$app_arg_1 = 1'd1;

  assign c$result_rec = c$app_arg_1 + c$app_arg;

  // register begin
  always @(posedge eta or  posedge  eta1) begin : c$app_arg_register
    if ( eta1) begin
      c$app_arg <= 1'd0;
    end else if (eta2) begin
      c$app_arg <= c$app_arg_0;
    end
  end
  // register end

  // register begin
  always @(posedge eta or  posedge  eta1) begin : c$app_arg_0_register
    if ( eta1) begin
      c$app_arg_0 <= 1'd0;
    end else if (eta2) begin
      c$app_arg_0 <= c$result_rec;
    end
  end
  // register end

  // register begin
  always @(posedge eta or  posedge  eta1) begin : c$app_arg_1_register
    if ( eta1) begin
      c$app_arg_1 <= 1'd1;
    end else if (eta2) begin
      c$app_arg_1 <= c$result_rec;
    end
  end
  // register end

  assign result = c$result_rec;


endmodule

