/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable

      // Outputs
    , output wire signed [7:0] result
    );
  reg [55:0] r = {8'sd1,   8'sd2,   8'sd3,   8'sd4,   8'sd5,   8'sd6,   8'sd7};
  wire [55:0] c$r_app_arg;

  // register begin
  always @(posedge clk or  posedge  rst) begin : r_register
    if ( rst) begin
      r <= {8'sd1,   8'sd2,   8'sd3,   8'sd4,   8'sd5,   8'sd6,   8'sd7};
    end else if (en) begin
      r <= c$r_app_arg;
    end
  end
  // register end

  assign result = $signed(r[56-1 -: 8]);

  // rotateLeftS begin
  localparam shift_amount = 1 % 7;

  generate
  if (shift_amount == 0) begin : no_shift
    assign c$r_app_arg = r;
  end else begin : do_shift
    assign c$r_app_arg = {r[((7-shift_amount)*8)-1 : 0]
                     ,r[56-1 : (7-shift_amount)*8]
                     };
  end
  endgenerate
  // rotateLeftS end


endmodule

